directory: /home/ad/dumeuri/DeepChange/MMDC_OE/train
mod_df: null
ex_dir: /home/ad/dumeuri/DeepChange/MMDC_OE/PT_FORMAT_4/train
s2_tile: ["31TDL","31TEN","32UQD","33UXR","34TFR"] # ["30TYR","31TEK","32TNR","32UPC","33TXK","34UDB"]
s2_max_ccp: 0.5
opt: s1s2
crop_size: 128
repeat: 4
l_possible_months: [6,7,8,9,10,11,12]