defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

path_geojson:  /home/ad/dumeuri/DeepChange/PASTIS_CD/PASTIS_CD/
path_global_dir: /home/ad/dumeuri/DeepChange/PASTIS_CD/PASTIS_CD/
s2_tile: T31TFM
max_cc: null
hydra:
  output_subdir: null
  run:
    dir: .
