defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

where: local
path_csv: /media/dumeuri/DATA/Data/Iris/MMDC_OE/reporting_export_20230522.csv
ex_dir: /media/dumeuri/DATA/Data/Iris/MMDC_OE/

hydra:
  output_subdir: null
  run:
    dir: .
