defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

year: 2017
pattern: pretrain_train*.geojson
geojson_dir: /home/dumeuri/Documents/dataset/datacubes/non_overlap_geojson
id: 6
opt: s2
agera_band: null
max_cc: 100

hydra:
  output_subdir: null
  run:
    dir: .
