defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

roi_size: 1280 #in meters
n_roi: 30
s2_tile: ["30TYR","31TEK","32TNR","32UPC","33TXK","34UDB"]
ex_dir: /home/dumeuri/Documents/
path_s2_shp: "/home/dumeuri/Documents/dataset/Sentinel-2-Shapefile-Index/sentinel_2_index_shapefile.shp"
dataset_type: val
hydra:
  output_subdir: null
  run:
    dir: .
