s2_tiles: [30TXT,31TEN, 31TDL,32UQD,33TYJ,33UXR,34TFR]
path_dir: /home/ad/dumeuri/DeepChange/MMDC_OE/PT_FORMAT_2/train
mod: s2
crop_size: 64
qmin: 0.05
max_img: 2
qmax: 0.95
ex_dir: /home/ad/dumeuri/DeepChange/MMDC_OE
